apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
  - port: 80          # Service port
    targetPort: 8080  # Container port
    nodePort: 30000   # NodePort
  selector:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend