apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  containers:
  - name: webapp
    image: 444868690040.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1-webapp-repo:v0.1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    env:
    - name: DBPORT
      value: "3306"              # MySQL service port
    - name: DBHOST
      value: "mysql"    # This is the actual MySQL service name
    - name: DBUSER
      value: "root"              
    - name: DBPWD
      value: "root_password"     # MYSQL_ROOT_PASSWORD
    ports:
    - containerPort: 8080        # Port of frontend app
