apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1  # 1 is the default value
  template:
    metadata:
      labels:
        app: mysql
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: mysql
        image: 444868690040.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1-mysql-repo:v0.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root_password"
        - name: MYSQL_DATABASE
          value: "my_database"  
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306